FROM python:3.11-slim

# Installer dépendances système pour FAISS
RUN apt-get update && apt-get install -y \
    build-essential \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

# Installer FAISS CPU officiel
RUN pip install faiss-cpu

# Copier ton projet
WORKDIR /app
COPY . /app

# Installer dépendances Python
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
